#!/bin/bash

FILEPATH=$(cd "$(dirname "$0")"; pwd)/`basename $0`
if [[ -h $FILEPATH ]]; then
  REALPATH=`readlink $FILEPATH`
else
  REALPATH=$FILEPATH
fi

RUNIT_DIR=$(dirname $REALPATH)
source $RUNIT_DIR/config

cd $RAILS_ROOT
test `which bluepill` || (echo "Please install bluepill through rubygems if possible for faster execution")
test `which bluepill` && bluepill --no-privileged -c $BLUEPILL_HOME $* || bundle exec bluepill --no-privileged -c $BLUEPILL_HOME $*