#!/bin/bash

FILEPATH=$(cd "$(dirname "$0")"; pwd)/`basename $0`
if [[ -h $FILEPATH ]]; then
  REALPATH=`readlink $FILEPATH`
else
  REALPATH=$FILEPATH
fi

RUNIT_DIR=$(dirname $REALPATH)
source $RUNIT_DIR/config

if [[ ! -h $SVDIR/$APP_NAME ]]; then
  ln -s $RUNIT_DIR/app $SVDIR/$APP_NAME
  echo "Installed $SVDIR/$APP_NAME"
else
  echo "Did NOT install $SVDIR/$APP_NAME since it was already present"
fi

if [[ ! -h $SVDIR/${APP_NAME}_bluepill ]]; then
  ln -s $RUNIT_DIR/bluepill $SVDIR/${APP_NAME}_bluepill
  echo "Installed $SVDIR/${APP_NAME}_bluepill"
else
  echo "Did NOT install $SVDIR/${APP_NAME}_bluepill since it was already present"
fi
